[package]
name = "verbose-bool"
version = "0.1.0"
authors = ["Pieter Bellens <pbellens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
